import os
import subprocess

class CriuRestorer:
    """ Class restoring CRiU dumps generated by CRiU dumper """

    def __init__(self):
        self.dump_folder_path_string= os.getcwd()+ "/CriuDumps"
        self.list_of_dumps = []

    def __get_list_of_dump_files(self):
        """ Goes to the CriuDumps folder and gets all avaliable files from within"""

        result = subprocess.run(["ls", "\CriuDumps"])
        print(result)


    
